// Help content for context-sensitive help system
export interface HelpContent {
  id: string;
  title: string;
  description: string;
  category?: string;
}

export const helpContent: Record<string, HelpContent> = {
  // Dashboard
  'dashboard-status-ris': {
    id: 'dashboard-status-ris',
    title: 'RIS Status',
    description: 'Shows the connection status to the RIPE RIS (Routing Information Service) route collectors. RIS provides real-time BGP routing data from multiple global vantage points.',
    category: 'dashboard',
  },
  'dashboard-status-rpki': {
    id: 'dashboard-status-rpki',
    title: 'RPKI Status',
    description: 'Displays the status of RPKI (Resource Public Key Infrastructure) validation. RPKI helps prevent BGP hijacks by cryptographically validating route announcements.',
    category: 'dashboard',
  },
  'dashboard-status-container': {
    id: 'dashboard-status-container',
    title: 'Container Health',
    description: 'Indicates whether the BGPalerter monitoring service is running properly. A healthy status means all monitoring processes are active and functioning correctly.',
    category: 'dashboard',
  },
  'dashboard-monitor-card': {
    id: 'dashboard-monitor-card',
    title: 'Monitor Status',
    description: 'Shows the status of individual BGP monitoring modules. Each monitor tracks specific types of BGP events such as hijacks, path changes, visibility issues, and new prefix announcements.',
    category: 'dashboard',
  },
  'dashboard-alerts-table': {
    id: 'dashboard-alerts-table',
    title: 'Recent Alerts',
    description: 'Displays the most recent BGP alerts detected by the monitoring system. Alerts are categorized by severity (critical, warning, info) and can be acknowledged or resolved.',
    category: 'dashboard',
  },
  'dashboard-auto-refresh': {
    id: 'dashboard-auto-refresh',
    title: 'Auto-Refresh',
    description: 'When enabled, the dashboard automatically refreshes every 30 seconds to show the latest monitoring data. Disable this if you want to manually control when data is updated.',
    category: 'dashboard',
  },

  // Alert History
  'alerts-severity-filter': {
    id: 'alerts-severity-filter',
    title: 'Severity Filter',
    description: 'Filter alerts by severity level: Critical (requires immediate attention), Warning (potential issues), or Info (informational events).',
    category: 'alerts',
  },
  'alerts-status-filter': {
    id: 'alerts-status-filter',
    title: 'Status Filter',
    description: 'Filter alerts by their current status: All (show everything), Unresolved (active alerts), Resolved (fixed alerts), or Acknowledged (alerts that have been seen but not yet resolved).',
    category: 'alerts',
  },
  'alerts-acknowledge-button': {
    id: 'alerts-acknowledge-button',
    title: 'Acknowledge Alert',
    description: 'Mark this alert as acknowledged to indicate you have seen it and are aware of the issue. Acknowledged alerts remain visible until they are resolved.',
    category: 'alerts',
  },
  'alerts-resolve-button': {
    id: 'alerts-resolve-button',
    title: 'Resolve Alert',
    description: 'Mark this alert as resolved when the underlying BGP issue has been fixed or mitigated. Resolved alerts are archived but remain searchable.',
    category: 'alerts',
  },

  // Alert Rules
  'rules-rule-type': {
    id: 'rules-rule-type',
    title: 'Rule Type',
    description: 'Select the type of BGP condition to monitor: Prefix Length (changes in prefix size), AS Path Pattern (specific routing paths), ROA Mismatch (RPKI validation failures), Announcement Rate (unusual announcement frequency), or Custom (define your own conditions).',
    category: 'rules',
  },
  'rules-conditions': {
    id: 'rules-conditions',
    title: 'Rule Conditions',
    description: 'Define the specific conditions that will trigger this alert rule. You can add multiple conditions that must all be met for the rule to fire. Each condition consists of a field, an operator, and a value.',
    category: 'rules',
  },
  'rules-severity': {
    id: 'rules-severity',
    title: 'Alert Severity',
    description: 'Set the severity level for alerts generated by this rule. Critical alerts require immediate attention, Warning alerts indicate potential issues, and Info alerts are for informational purposes.',
    category: 'rules',
  },
  'rules-notification-channels': {
    id: 'rules-notification-channels',
    title: 'Notification Channels',
    description: 'Choose which notification channels will receive alerts when this rule is triggered. You can select multiple channels including Email, Microsoft Teams, Slack, and Discord.',
    category: 'rules',
  },
  'rules-enable-toggle': {
    id: 'rules-enable-toggle',
    title: 'Enable/Disable Rule',
    description: 'Toggle this rule on or off. Disabled rules will not evaluate conditions or generate alerts, but their configuration is preserved for future use.',
    category: 'rules',
  },

  // Routing Data
  'routing-announced-prefixes': {
    id: 'routing-announced-prefixes',
    title: 'Announced Prefixes',
    description: 'View all IP prefixes currently announced by your AS (Autonomous System) as seen by RIS route collectors. This shows what routes are visible in the global BGP routing table.',
    category: 'routing',
  },
  'routing-as-path-info': {
    id: 'routing-as-path-info',
    title: 'AS Path Information',
    description: 'Displays the AS path for a specific prefix, showing the sequence of autonomous systems that traffic traverses to reach the destination. Useful for understanding routing relationships and detecting path anomalies.',
    category: 'routing',
  },
  'routing-bgp-updates': {
    id: 'routing-bgp-updates',
    title: 'BGP Updates',
    description: 'Shows recent BGP UPDATE messages for your AS, including announcements (new routes) and withdrawals (removed routes). This provides real-time visibility into routing changes.',
    category: 'routing',
  },

  // Administration
  'admin-email-config': {
    id: 'admin-email-config',
    title: 'Email Configuration',
    description: 'Configure email notification settings for BGP alerts. Add recipient email addresses and generate the configuration snippet to add to your BGPalerter config.yml file.',
    category: 'administration',
  },
  'admin-notification-settings': {
    id: 'admin-notification-settings',
    title: 'Notification Settings',
    description: 'Configure webhook integrations for Microsoft Teams, Slack, and Discord. Enable channels, add webhook URLs, and test notifications to ensure proper delivery of BGP alerts.',
    category: 'administration',
  },
  'admin-test-notification': {
    id: 'admin-test-notification',
    title: 'Test Notification',
    description: 'Send a test notification to verify that your webhook configuration is working correctly. This helps ensure you will receive alerts when real BGP events occur.',
    category: 'administration',
  },
  'admin-config-files': {
    id: 'admin-config-files',
    title: 'Configuration Files',
    description: 'View and edit BGPalerter configuration files directly from the dashboard. Changes can be saved and version history is maintained for rollback if needed.',
    category: 'administration',
  },
};

export function getHelpContent(id: string): HelpContent | undefined {
  return helpContent[id];
}

export function getHelpContentByCategory(category: string): HelpContent[] {
  return Object.values(helpContent).filter(content => content.category === category);
}
